version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
    links:
      - redis
    command: npm run dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
      - /user/app/node_modules
    environment:
      NODE_END: dev
      PORT: 3001
  
  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: admin
